[package]
name = "new_vegas"
version = "0.3.0"
authors = ["Alec Burgdorf <aeburgd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
fake = "2.2.0"
